import {
  recoverTypedDataAddress,
  type Address,
  type Hex,
  type WalletClient,
} from "viem";

/**
 * CascadeReceipt — a composite's signed attestation of the full upstream
 * payment graph generated by serving one buyer call.
 *
 * The composite signs this via EIP-712 and returns it (base64-encoded) in the
 * `X-Cascade-Receipt` HTTP response header alongside the standard x402
 * response. Any consumer — another agent, a UI, an indexer, a contract that
 * adopts the format — can verify the signature against the composite's known
 * wallet and trust the claimed payment graph without trusting the server.
 *
 * This replaces heuristic cascade matching (scan AuthorizationUsed events in a
 * block window and hope) with a cryptographic proof the composite itself has
 * attested to.
 *
 * Design goals:
 *   - Deterministic: the composite signs one receipt per call; replay is
 *     prevented by (receiptId, chainId, verifyingContract).
 *   - Portable: the struct is HTTP-header-size friendly after base64. On an
 *     average 3-upstream composite the receipt is ~700-900 bytes unencoded.
 *   - Verifiable by tx-hash cross-check: each UpstreamPayment carries the
 *     on-chain settlement tx. An honest indexer can re-query the chain for
 *     those txs and confirm they match the claim.
 *   - Registry-compatible: CascadeLedger.sol accepts the exact same struct,
 *     so an on-chain submission path exists when callers want permanence.
 */

export interface UpstreamPayment {
  /** Stable identifier for the upstream (e.g. "wallet-risk"). */
  slug: string;
  /** Author wallet that received payment. */
  author: Address;
  /** Amount paid, in settlement-token base units. */
  amount: bigint;
  /** On-chain settlement tx hash on the cascade chain. */
  settlementTx: Hex;
}

export interface CascadeReceipt {
  /** Composite signal's wallet (the EIP-712 signer). */
  composite: Address;
  /** Deterministic receipt id: keccak256(buyer, buyerSettlementTx). */
  receiptId: Hex;
  /** Address that paid the composite. */
  buyer: Address;
  /** Amount the buyer paid, base units. */
  buyerAmount: bigint;
  /** Settlement token (e.g. bUSD). */
  settlementToken: Address;
  /** On-chain tx where the buyer's x402 payment settled. */
  buyerSettlementTx: Hex;
  /** Fan-out to upstream authors, in the order the composite paid them. */
  upstreams: UpstreamPayment[];
  /** Unix seconds. */
  timestamp: bigint;
  /** Chain id the receipt's settlements live on. */
  chainId: bigint;
}

/** EIP-712 domain for cascade receipts. `verifyingContract` is the CascadeLedger. */
export interface CascadeDomain {
  name: string;
  version: string;
  chainId: bigint;
  verifyingContract: Address;
}

/**
 * Canonical domain for Beacon cascade receipts. When no on-chain CascadeLedger
 * is deployed for a chain, `verifyingContract` is the zero address — the
 * receipt still verifies but consumers know settlement is off-chain-only.
 */
export function buildCascadeDomain(
  chainId: bigint,
  ledgerAddress: Address = "0x0000000000000000000000000000000000000000"
): CascadeDomain {
  return {
    name: "Beacon CascadeReceipt",
    version: "1",
    chainId,
    verifyingContract: ledgerAddress,
  };
}

/** EIP-712 type definitions. Must stay in sync with CascadeLedger.sol. */
export const CASCADE_RECEIPT_TYPES = {
  UpstreamPayment: [
    { name: "slug", type: "string" },
    { name: "author", type: "address" },
    { name: "amount", type: "uint256" },
    { name: "settlementTx", type: "bytes32" },
  ],
  CascadeReceipt: [
    { name: "composite", type: "address" },
    { name: "receiptId", type: "bytes32" },
    { name: "buyer", type: "address" },
    { name: "buyerAmount", type: "uint256" },
    { name: "settlementToken", type: "address" },
    { name: "buyerSettlementTx", type: "bytes32" },
    { name: "upstreams", type: "UpstreamPayment[]" },
    { name: "timestamp", type: "uint256" },
    { name: "chainId", type: "uint256" },
  ],
} as const;

export interface SignedCascadeReceipt {
  receipt: CascadeReceipt;
  signature: Hex;
  /** Domain the signature was produced against. Consumers need it to verify. */
  domain: CascadeDomain;
}

/** Signs a cascade receipt with the composite's wallet. */
export async function signCascadeReceipt(
  walletClient: WalletClient,
  receipt: CascadeReceipt,
  domain: CascadeDomain
): Promise<SignedCascadeReceipt> {
  const account = walletClient.account;
  if (!account) throw new Error("walletClient has no account");
  if (account.address.toLowerCase() !== receipt.composite.toLowerCase()) {
    throw new Error("signer address does not match receipt.composite");
  }
  const signature = await walletClient.signTypedData({
    account,
    domain: {
      name: domain.name,
      version: domain.version,
      chainId: Number(domain.chainId),
      verifyingContract: domain.verifyingContract,
    },
    types: CASCADE_RECEIPT_TYPES,
    primaryType: "CascadeReceipt",
    message: serializeReceiptForTypedData(receipt),
  });
  return { receipt, signature, domain };
}

/** Verifies a signed cascade receipt. Returns the recovered signer address. */
export async function verifyCascadeReceipt(
  signed: SignedCascadeReceipt
): Promise<Address> {
  const recovered = await recoverTypedDataAddress({
    domain: {
      name: signed.domain.name,
      version: signed.domain.version,
      chainId: Number(signed.domain.chainId),
      verifyingContract: signed.domain.verifyingContract,
    },
    types: CASCADE_RECEIPT_TYPES,
    primaryType: "CascadeReceipt",
    message: serializeReceiptForTypedData(signed.receipt),
    signature: signed.signature,
  });
  if (recovered.toLowerCase() !== signed.receipt.composite.toLowerCase()) {
    throw new Error(
      `cascade receipt signature does not match composite (got ${recovered}, expected ${signed.receipt.composite})`
    );
  }
  return recovered;
}

function serializeReceiptForTypedData(r: CascadeReceipt) {
  return {
    composite: r.composite,
    receiptId: r.receiptId,
    buyer: r.buyer,
    buyerAmount: r.buyerAmount,
    settlementToken: r.settlementToken,
    buyerSettlementTx: r.buyerSettlementTx,
    upstreams: r.upstreams.map((u) => ({
      slug: u.slug,
      author: u.author,
      amount: u.amount,
      settlementTx: u.settlementTx,
    })),
    timestamp: r.timestamp,
    chainId: r.chainId,
  };
}

/**
 * Encodes a signed receipt for transport in HTTP response headers. Uses
 * base64url so the value is URL- and header-safe. BigInts are stringified
 * for JSON portability; consumers restore them via `decodeCascadeReceiptHeader`.
 */
export function encodeCascadeReceiptHeader(signed: SignedCascadeReceipt): string {
  const payload = {
    receipt: {
      ...signed.receipt,
      buyerAmount: signed.receipt.buyerAmount.toString(),
      timestamp: signed.receipt.timestamp.toString(),
      chainId: signed.receipt.chainId.toString(),
      upstreams: signed.receipt.upstreams.map((u) => ({
        ...u,
        amount: u.amount.toString(),
      })),
    },
    signature: signed.signature,
    domain: {
      ...signed.domain,
      chainId: signed.domain.chainId.toString(),
    },
  };
  return Buffer.from(JSON.stringify(payload)).toString("base64");
}

/** Inverse of `encodeCascadeReceiptHeader`. Returns a strongly-typed receipt. */
export function decodeCascadeReceiptHeader(header: string): SignedCascadeReceipt {
  const obj = JSON.parse(Buffer.from(header, "base64").toString("utf-8")) as {
    receipt: {
      composite: Address;
      receiptId: Hex;
      buyer: Address;
      buyerAmount: string;
      settlementToken: Address;
      buyerSettlementTx: Hex;
      upstreams: Array<{
        slug: string;
        author: Address;
        amount: string;
        settlementTx: Hex;
      }>;
      timestamp: string;
      chainId: string;
    };
    signature: Hex;
    domain: {
      name: string;
      version: string;
      chainId: string;
      verifyingContract: Address;
    };
  };
  return {
    receipt: {
      ...obj.receipt,
      buyerAmount: BigInt(obj.receipt.buyerAmount),
      timestamp: BigInt(obj.receipt.timestamp),
      chainId: BigInt(obj.receipt.chainId),
      upstreams: obj.receipt.upstreams.map((u) => ({
        ...u,
        amount: BigInt(u.amount),
      })),
    },
    signature: obj.signature,
    domain: {
      ...obj.domain,
      chainId: BigInt(obj.domain.chainId),
    },
  };
}

/**
 * Derives the deterministic receiptId for a buyer call. Matches
 * CascadeLedger._receiptId on-chain.
 */
export function computeReceiptId(buyer: Address, buyerSettlementTx: Hex): Hex {
  // keccak256(abi.encodePacked(buyer, buyerSettlementTx))
  // viem doesn't ship a synchronous helper, so we inline the encoding via
  // `encodePacked` + `keccak256` from the package entrypoint.
  const concat = buyer.toLowerCase().slice(2).padStart(40, "0") +
    buyerSettlementTx.toLowerCase().slice(2).padStart(64, "0");
  // Dynamic import to avoid a cycle at module load; viem is already a peer dep.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { keccak256 } = require("viem");
  return keccak256(`0x${concat}` as Hex);
}
